#!/bin/bash

#######################################################################################################
####################################### images ########################################################
#######################################################################################################

# json=$1
# string=$(echo ${json} | jq '.images[]'| tr -d '"')
#
# echo "images $json"

read -a array <<< $1

# loop
for i in "${array[@]}"
  do

  echo "image downloading from $i"

# get url
  url=$i
# get file
  curl -O -# $url
# get file name
  fullname=$(basename "$url")
  filename=$(echo $fullname | cut -f 1 -d '.')
  echo "filename $filename"
  mv $fullname $filename.png

# get image size
  width3=$(identify -ping -format '%w' $filename.png)
  height3=$(identify -ping -format '%h' $filename.png)

# calculate size for 2x image
  width2=$(($width3*2/3))
  height2=$(($height3*2/3))

# calculate size for 1x image
  width=$(($width3*1/3))
  height=$(($height3*1/3))

# create 3x image
  cp $filename.png $filename@3x.png
# create 2x image
  convert $filename.png    -resize $height2x$width2\> $filename@2x.png
# create 1x image
  convert $filename.png   -resize $heightx$width\> $filename.png

#move to image set folder
  mkdir temp
  mv $filename* temp
  mv temp $filename.imageset
done

#find path of Assets.xcassets
path=$(find tmp -path '*.xcassets')

# copy all image set to xcassets and delete temp files
cp -Rf *.imageset "$path" && rm -r *.imageset


#######################################################################################################
##################################### App Icon ########################################################
#######################################################################################################

echo "App icon downloading from $2"
curl -O -# $2
icon=$(basename "$2")

convert $icon    -resize 40x40\> Icon-20.0@2x.png
convert $icon    -resize 60x60\> Icon-20.0@3x.png
convert $icon    -resize 29x29\> Icon-29.0@1x.png
convert $icon    -resize 58x58\> Icon-29.0@2x.png
convert $icon    -resize 87x87\> Icon-29.0@3x.png
convert $icon    -resize 40x40\> Icon-40.0@1x.png
convert $icon    -resize 80x80\> Icon-40.0@2x.png
convert $icon    -resize 120x120\> Icon-40.0@3x.png
convert $icon    -resize 50x50\> Icon-50.0@1x.png
convert $icon    -resize 100x100\> Icon-50.0@2x.png
convert $icon    -resize 57x57\> Icon-57.0@1x.png
convert $icon    -resize 114x114\> Icon-57.0@2x.png
convert $icon    -resize 120x120\> Icon-60.0@2x.png
convert $icon    -resize 180x180\> Icon-60.0@3x.png
convert $icon    -resize 72x72\> Icon-72.0@1x.png
convert $icon    -resize 144x144\> Icon-72.0@2x.png
convert $icon    -resize 76x76\> Icon-76.0@1x.png
convert $icon    -resize 152x152\> Icon-76.0@2x.png
convert $icon    -resize 167x167\> Icon-83.5@2x.png

path=$(find tmp -path '*.appiconset')
mv Icon-* "$path"
rm $icon
